language: python

python:
    - "2.7"

branches:
  only:
    - master

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - make
    - coverage run --source=yast runtests.py

after_success:
    - coveralls

